stages:
  - build
  - backend-test

# Build stage
build:
  image: "node:18"
  stage: build
  script:
    - echo "Installing dependencies"
    - npm install

# Build stage
backend-test:
  image: "node:18"
  stage: backend-test
  script:
    - echo "Testing"
    - npm install
    - cd amplify/backend/function/usersLambda/src && npm install && cd ../../../..
    - cd amplify/backend/function/appointmentsLambda/src && npm install && cd ../../../..
    - cd amplify/backend/function/articlesLambda/src && npm install && cd ../../../..
    - npm test