stages:
  - build
  - backend-test

# Build stage
build:
  image: "node:18"
  stage: build
  script:
    - echo "Installing dependencies"
    - sudo apt-get update
    - npm install
    - npm install -g @aws-amplify/cli
    - sudo apt-get install jq


backend-test:
  image: "node:18"
  stage: backend-test
  script:
    - echo "Testing"
    - sudo apt-get install jq
    - amplify mock function usersLambda --event src/event.json --timeout 20 > outputs.txt
    - awk '/{/,/} /' outputs.txt | tail -n +4 | head -n -1 > outputs.json
    - status_code=$(jq -r '.statusCode' outputs.json)
    - if [[ "$status_code">=200 && "$status_code"<300 ]]; then
    -   echo "Status failed";
    -   exit 1; # Fail the pipeline
    - fi